# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build wheel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install frontend dependencies with Bun
        run: bun install
        working-directory: ./frontend

      - name: Build frontend with Bun
        run: bun run build
        working-directory: ./frontend

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: '3.13'

      - name: Install dependencies with uv
        run: uv sync

      - name: Build package with uv
        run: uv build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel
          path: ./dist
