# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Frontend

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        working-directory: ./frontend

      - name: Build app
        run: bun run build
        working-directory: ./frontend

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: vite-app
          path: |
            ./frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: vite-app

#      - name: Login to Azure
#        uses: azure/login@v2
#        with:
#          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CDB9B05DF30849BB81ABEA0EB0B7D045 }}
#          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D5EA7E06D4AC481FA9756EC3A32F321D }}
#          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D69F0204E32B417782796369C8847197 }}

#      - name: 'Deploy to Azure Web App'
#        uses: azure/webapps-deploy@v3
#        id: deploy-to-webapp
#        with:
#          app-name: 'magic-8-vite'
#          slot-name: 'Production'
